### ISSUE TITLE
Unescaped left brace in regex is illegal in regex

### ISSUE THREAD

**Issue by eserte** [renatocron/Stash-REST#2]
Tests fail with perl 5.25.1 and later:

```
Unescaped left brace in regex is illegal in regex; marked by <-- HERE in m/Please, use only { <-- HERE params} instead/ at t/basic.t line 364.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/basic.t .............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 1 subtests passed 
```

**Comment by jkeenan** [comment]
This is a bug report for:

Stash-REST-0.10

Due to unescaped left braces in some regular expression patterns in your code, your module won't work on 5.26.0. The CPAN Tester automated testing service cannot test your distribution on new versions of Perl until it is fixed and any modules that depend on yours will not work either.  Please see:

http://matrix.cpantesters.org/?dist=Stash-REST

Here is a link to all modules that depend on yours:

http://deps.cpantesters.org/depended-on-by.pl?dist=Stash-REST

We would appreciate help in sorting this out before the new version of Perl is released in May of this year. These errors are quite easy to correct and I would be happy to lend a hand.

I'm including a log file of my failure to build and install using "cpanm".

Thanks!

Jim Keenan
[stash-rest.log.pdf](https://github.com/renatocron/Stash-REST/files/693655/stash-rest.log.pdf)

**Comment by renatocron** [comment]
Fixed
